delphai/helm-charts

charts/delphai-keda/Chart.yaml, charts/delphai-keda/templates/ingress.yml, charts/delphai-streaming/Chart.yaml
`Notifications` service is deployed now onto `review`/`pink` with this chart:
```
$ kubectl describe mapping notifications 
Name:         notifications
Namespace:    notifications
Kind:         Mapping
Spec:
Host:             api.delphai.pink
Prefix:           /notifications/
Service:          notifications:8000
Cors:
Credentials:    true
Headers:        Origin, Content-Type, Accept, Authorization, X-Request-With, X-GENERAL-TOKEN, x-grpc-web,grpc-timeout
max_age:        86400
Methods:        GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH
Origins:        https://app.delphai.pink
```
It works in Firefox, Chrome, Safari. Hope we accessing these endpoints only from `app.delphai.*`
=> V1-4978 Enable CORS for main domain, enable PATCH method

charts/delphai-keda/Chart.yaml, charts/delphai-keda/templates/deployment.yml, charts/delphai-keda/values.yaml
Now applied on https://ml-tools.delphai.pink/ , works as expected
=> DEVOPS-27 Require Keycloak roles for OAuth

charts/delphai-keda/templates/scaled-object.yml
Loki stack is not used anymore (in terms off stack), only its separate components.
That’s why auto scaling dependent on loki's Prometheus address is broken and needs to be fixed.
=> Change prometheus server address

charts/delphai-keda/Chart.yaml, charts/delphai-keda/templates/ingress.yml
I've removed all subdomains definition so all Mappings are now in the only Host — that even reduced amount of routes.
But for every mapping it checks the hostname, so it doesn't cause collisions.
I've also added the prefix route in addition to subdomain.
It's already applied to all review deployments and to one on staging — everything works including new prefix
=> DEVOPS-193 DEVOPS-194 Prefix route

charts/delphai-keda/Chart.yaml, charts/delphai-keda/templates/deployment.yml, charts/delphai-keda/values.yaml
Adding `preferGpu` in case of apps that would prefer to use GPU nodes. Here the requirement is soft as it's just a preference - in case it's not possible to schedule on a GPU node, it will be done on another node type. 
`affinity: `  here is moved out of the `if` blocks, and in the case where `preferGpu` and `onePodMaxPerNodePerApp` are both `false`, affinity is then considered empty and isn't reflected in the actual deployment.
Changes have been tested on review for translation and GPU nodes are indeed being preferred.
=> DEVOPS-255 add GPU preference affinity

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml, charts/delphai-keda/Chart.yaml, charts/delphai-keda/templates/deployment.yml
It turns out that AKS enforces CPU limit very strict
Lets relax the limit then
=> DEVOPS-283 Allow OAuth proxy to use more CPU

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml
That allows to define
```yaml
debugMode:
enabled: true
command:
command: ""
command: ~
command: null
```
to NOT override the entrypoint in debug mode. Same for `args`
I've tested it, it works fine
=> DEVOPS-311 Customize debug mode values

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml, charts/delphai-deployment/values.yaml
Readiness probes tested with all ports and options.
Since gRPC is deprecated, before merging, we have to make sure that all gRPC services expose the `httpgateway` port as well and remove the relevant parts.
=> DEVOPS-404 feat: add readiness probe

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml
Confirmed that the JWT is provided by Keycloak by testing on review using an image of `ml-tools` with the `--set-xauthrequest` option enabled.
=> DEVOPS-414 enable `--pass-access-token` for `oauth2-proxy`

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml, charts/delphai-deployment/values.yaml
* temporarily move default secret envvar to template
=> DEVOPS-416 refactor: disable default `mongo-credentials`

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml
Made redundant by the addition of k8s-device-plugin. Confirmed that GPU workloads work fine without them:
=> refactor: remove redundant nvidia envvars

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml, charts/delphai-deployment/values.yaml
This reverts commit 1303f34f01bdc00fb84f3bbec1cdde9bd53d1d69.
Something went wrong with the release of the page-scraper. We need to make sure that no-one picks up 0.2.18 while I investigate more.
=> Revert "chore: redis as Deployment, not StatefulSet. (#69)"

charts/delphai-deployment/Chart.lock, charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/values.yaml
In this PR we change the redis workload kind from the default `StatefulSet` to a simpler `Deployment`.
During the deployment, new redis-master pods will be created, but the `[service]-redis-master` Service will stay the same, and the new `Endpoints` will be practically identical to the old ones - with the same labels, only with different timestamp metadata etc.
===
Tested on review using the page-scraper service `https://app.delphai.pink/service/page-scraper-deployment-kind/`
===
As a side-note, the `Chart.lock` gets updated to specify that we deploy redis based on Chart 17.17.1, not an older version. This is what actually is used in production.
=> Redis as a Deployment kind

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml
The env variable points at the correct auth server, e.g. our Keycloak.
=> feat: new optional env variable OIDC_BASE_URL.

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml
Traffic inside the k8s cluster is faster and simpler than accessing a public IP.
=> feat: Keycloak OIDC is available as an internal k8s Service.

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/deployment.yaml
This fixes authentication in Swagger GUI apps served by several backend services. Swagger GUI runs in the developer's browser, not in a k8s cluster.
=> fix: external DNS for Keycloak OIDC access.

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/NOTES.txt
This change is a small DevX quality of life improvement.
Sample usage:
```
Release "companies-tadek-test-deployment" has been upgraded. Happy Helming!
NAME: companies-tadek-test-deployment
LAST DEPLOYED: Thu Oct 31 11:25:30 2024
NAMESPACE: companies
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
This service exposes following endpoint(s):
* HTTPS: https://app.delphai.pink/service/companies-tadek-test-deployment/ 
* Public API: https://api.delphai.pink/companies-tadek-test-deployment/v1/companies/
* GRPC: companies-tadek-test-deployment.grpc.delphai.pink:80
```
=> CROS-1441 NOTES.txt documents public API

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/mapping.yaml
This PR configures CORS for the public API endpoints. The work in this PR is based on modifications which Anton recently made in production Mappings.
It can be tested with a test deployment of `docs` that uses a test deployment of `companies` here: https://docs-tadek-test-deployment.delphai.pink/
For reference, the Azure API Management had:
```
<cors>
<allowed-origins>
<origin>*</origin>
</allowed-origins>
<allowed-methods>
<method>GET</method>
<method>POST</method>
</allowed-methods>
<allowed-headers>
<header>Origin</header>
<header>Content-Type</header>
<header>Accept</header>
<header>Authorization</header>
</allowed-headers>
</cors>
```
=> feat: CORS configuration for public API

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/mapping.yaml
The JavaScript code of the Add-In is hosted on a cross-site location https://delphaiexceladdinreview.z6.web.core.windows.net. In this change we whitelist that Origin.
We also lower the CORS Cache TTL to make future changes easier.
=> feat: public API CORS allows Excel Add-In origin

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/mapping.yaml
No need to override that in a Mapping
=> chore: 60s is now default timeout.

charts/delphai-deployment/Chart.yaml, charts/delphai-deployment/templates/cron-job.yaml
Dev branch releases will now create suspended CronJobs, that can be manually triggered for testing purposes.
=> DDEVOPS-719: suspended CronJobs for dev branch releases.
